version: "3.6"
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: msg_to_table
        restart: always
        image: msg_to_table:1.0.0
        ports:
            - "57990:7990" #host:container

